/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ActionButton({ text, primary }) {
  const baseClasses = "px-8 py-4 max-md:px-5";
  const primaryClasses = "text-white bg-blue-600";
  const secondaryClasses = "text-black whitespace-nowrap bg-white";

  return (
    <button
      className={`${baseClasses} ${
        primary ? primaryClasses : secondaryClasses
      }`}
    >
      {text}
    </button>
  );
}

export default ActionButton;
