/**
 * This code was generated by Builder.io.
 */
import React from "react";

const logos = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/045ff0b24851ec38a3c0d701d03f19f1b48cb50ff81ceb53e4d9b7cf6befc929?placeholderIfAbsent=true&apiKey=4347c25cbbc84e04bdff1e95b941b3c7",
    alt: "Partner logo 1",
    width: 130,
    aspect: 1.88,
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/2fa6632ae9d90d51f4a5f9515cd36cf9e1720615dca385f6d917235b2a1b7b2b?placeholderIfAbsent=true&apiKey=4347c25cbbc84e04bdff1e95b941b3c7",
    alt: "Partner logo 2",
    width: 130,
    aspect: 1.88,
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f146ec6d02286d8e883d09719ab5f4c0e330782fdc35dca55db25828d74be6d3?placeholderIfAbsent=true&apiKey=4347c25cbbc84e04bdff1e95b941b3c7",
    alt: "Partner logo 3",
    width: 131,
    aspect: 1.9,
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e89377c5ac687360e12466b9660570184fcd49ec3a467e5e37b9d07a3aa2cc86?placeholderIfAbsent=true&apiKey=4347c25cbbc84e04bdff1e95b941b3c7",
    alt: "Partner logo 4",
    width: 129,
    aspect: 1.87,
  },
];

function PartnerLogos() {
  return (
    <div className="flex flex-wrap gap-5 mt-9">
      {logos.map((logo, index) => (
        <img
          key={index}
          loading="lazy"
          src={logo.src}
          alt={logo.alt}
          className={`object-contain shrink-0 max-w-full w-[${logo.width}px]`}
          style={{ aspectRatio: logo.aspect }}
        />
      ))}
    </div>
  );
}

export default PartnerLogos;
