/**
 * This code was generated by Builder.io.
 */
import React from "react";

function GetServiceButton() {
  return (
    <button className="flex gap-3.5 px-8 py-4 mt-12 max-w-full text-sm text-center text-white bg-blue-600 border-2 border-blue-600 border-solid w-[155px] max-md:px-5 max-md:mt-10">
      <span className="font-semibold leading-3">Get Service</span>
      <span className="self-start font-black leading-none"></span>
    </button>
  );
}

export default GetServiceButton;
